spring.application.name=trilha-do-saber

spring.profiles.active=local

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
server.port=${PORT:8080}
spring.sql.init.mode=always
resend.api-key=${RESEND_API_KEY:}
resend.from=${RESEND_FROM:Trilha do Saber <onboarding@resend.dev>}