spring.datasource.url=jdbc:postgresql://localhost:5432/trilha_do_saber
spring.datasource.username=postgres
spring.datasource.password=1234

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=trilhadosaberpfc@gmail.com
spring.mail.password=senha-invalida-temporaria
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true