-- Esse arquivo ficou desatualizado: referenciava a tabela "tema" (removida) e a coluna
-- "ra" do aluno (o campo se chama "rgm"), o que quebrava a subida da aplicação porque
-- essas colunas/tabelas nao existem mais no schema atual.
--
-- A carga de dados de teste hoje é feita em Java, na subida da aplicação:
-- - CargaInicialDados: cria uma prova e as questões de exemplo
-- - CargaUsuariosIniciais: cria um admin e um coordenador de teste
